// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8YvpzMxGGxtm69KuiE1CzQUk7JOx54GY',
    appId: '1:64578926318:web:ed8924b75f98b97b8265ff',
    messagingSenderId: '64578926318',
    projectId: 'instaa-875e8',
    authDomain: 'instaa-875e8.firebaseapp.com',
    storageBucket: 'instaa-875e8.appspot.com',
    measurementId: 'G-8SDQ2L1EKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAot0QSAY8RIomMEVfQIB7JuLpiO5IoQpg',
    appId: '1:64578926318:android:6a72101369e38fc98265ff',
    messagingSenderId: '64578926318',
    projectId: 'instaa-875e8',
    storageBucket: 'instaa-875e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_fVNcEOqgBWye5lMG1Lt4ETgXc6dYut8',
    appId: '1:64578926318:ios:78299e22e28bbebc8265ff',
    messagingSenderId: '64578926318',
    projectId: 'instaa-875e8',
    storageBucket: 'instaa-875e8.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_fVNcEOqgBWye5lMG1Lt4ETgXc6dYut8',
    appId: '1:64578926318:ios:78299e22e28bbebc8265ff',
    messagingSenderId: '64578926318',
    projectId: 'instaa-875e8',
    storageBucket: 'instaa-875e8.appspot.com',
    iosBundleId: 'com.example.instagram',
  );
}
